FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.19-openshift-4.13 AS builder
WORKDIR /src/ovirt-csi-driver
COPY . .
RUN make build

FROM registry.ci.openshift.org/ocp/4.13:base

RUN yum install -y e2fsprogs xfsprogs
COPY --from=builder /src/ovirt-csi-driver/bin/ovirt-csi-driver .

ENTRYPOINT ["./ovirt-csi-driver"]
