@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String version = '4.21.0'
String imgTag  = "v" + version

olcnePipeline(
        branchPattern: new BranchPattern(master: 'release/.*', feature: '(?!^release/.*$)(^.*$)'),
        containers: [('container-registry.oracle.com/olcne/ovirt-csi-driver:' + imgTag): 'olcne/ovirt-csi-driver:' + imgTag],
        architectures: ['x86_64', 'aarch64'],
        platforms: ['ol9'],
        yumOL9Repos: ['ol9_UEKR8'],
        customPlatformStages: [
                customPlatformSteps: [
                        ol9: [container: [enabled: true ], buildContainerRpms: [enabled: true ]],
                ],
        ],
)

